### ISSUE TITLE
Update ISCC version

### ISSUE THREAD

**Issue by vldgeorgiev** [therion/therion-batteries#2]
Would it be possible to update the ISCC compiler version that you use for the automated build?
Yours seems to be v5.5.4, which is old and causes this problem https://mailman.speleo.sk/pipermail/therion/2017-April/006480.html
It doesn't process newer Inno directives and generates an invalid install path name.
I ran the tests with 5.5.9, which works OK.

![2017-04-18 23_57_59](https://cloud.githubusercontent.com/assets/5023226/25153166/3b1d85c6-2494-11e7-8b9a-2924fa066156.png)

**Comment by mbudaj** [comment]
We are using files from this repo for automated builds. They are extracted from InnoSetup 5.5.9. Maybe the preprocessor dll is missing? I'll check later.

**Comment by vldgeorgiev** [comment]
The preprocessor was missing and maybe some files were mixed (or my copy of them was mixed), because after an install it wrote v5.5.4 as installer version in the therion reg key.
I replaced all of the files now from a fresh Inno and it works and reports 5.5.9.

**Comment by mbudaj** [comment]
Adding preprocessor was enough, all other files were up to date.
